### PR TITLE
Copy fixes

### LINKED ISSUE #163: Copy & Design Issues
- [x] The 'see more' section that sits under the email button should sit under the bank account button.
- [x] The 'see more' filed that should sit under the Health Issues tile it is in a separate tile with no heading.
- [x] The 'see more' filed that should sit under the Limitations tile it is in a separate tile with no heading.
- [x] The logo is very small, can it be made bigger? 
- [x] The list of organsations gives the name of the person who has signed up, not the name of the organsation
- [x] Current copy reads: Enter your prefer back up email address in the event you leave the organisation; copy should read: Enter a back up email address that can be used to recover your organisation's information
- [x] The copy should read: Include a short label for what this contact channel is for e.g. Customer Support
- [x] Copy to be added to explain function- e.g. You can add your organsation's logo. Ideally the logo should be at least xx, and no bigger than xx. (Yalla to add size of image)
- [x] It should read: 
Government helpline
Monday to Friday, 8am to 6pm
0800 328 5644 (choose option 3)
- [x] needs to read valid passport in verify identity section
- [x] Hide how long does it take if empty
- [x] see more under blank box for "tell them about any limitation you have on getting work should be under this heading
- [x]  Copy should read (paragraph under 'Contact Details': If you want customers to be able to contact you if they need further help when using the UC helper please add the relevant phone number, email address or webchat link below. 
- [x] Copy should read: Include a short description for the contact  e.g. 'Customer Support Centre', or 'Benefit Advice Webchat'
- [x] see more under details of any capital, savings and investments comes out as tip. should this just be  standard see more box not "tip" to match other boxes
- [x] Copy should read: Benefit calculator link Enter the full web link (including http://) of your organisation's preferred benefit calculator here
- [x] click here in "Tip" doesn't work goes to blank web page
- [x] change email address for tips

### PR DESCRIPTION
**Pull request by thejoefriel**
#### Issues this PR relates to
Fixes #163 

=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

### CODE REVIEW

File: client/src/pages/Admin/Organisations/index.js [hunk 1]
```diff
@@ -119,6 +128,7 @@ const Organisations = () => {
   useEffect(() => {
     const getUsers = async () => {
       const { data, error } = await Users.getAdminUsers();
+      console.log('da', data);
```
Comment (RamyAlshurafa) [inline client/src/pages/Admin/Organisations/index.js:131]:
```suggestion
```

**Review by RamyAlshurafa — CHANGES_REQUESTED** [review]
- [ ] the bank account tip is in wrong place
Screenshot from 2021-09-06 11-07-40
- [ ] not sure if this is a bug but see more hide/show the tip https://www.loom.com/share/744b756e522d417b876013f023121613

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa that second point is fine as that tip is specific for that checklist item

**Review by RamyAlshurafa — APPROVED** [review]
